language: node_js
node_js: 8
  
install:
  - npm install
  
script:
  - hexo g

cache: npm

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: public
  on:
    branch: master
